### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by shrikantzarekar** [google/marzipano#49]
npm run dev is throwing errors. Please help

I think it says "scripts" is an unrecognized command, where the package.json has scripts : "scripts/dev"

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\s.zarekar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle marzipano@0.5.1~predev: marzipano@0.5.1
6 silly lifecycle marzipano@0.5.1~predev: no script for predev, continuing
7 info lifecycle marzipano@0.5.1~dev: marzipano@0.5.1
8 verbose lifecycle marzipano@0.5.1~dev: unsafe-perm in lifecycle true
9 verbose lifecycle marzipano@0.5.1~dev: PATH: C:\Users\s.zarekar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Shrikant\VR\Code\new\marzipano\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Ruby23-x64\bin;C:\MongoDB\bin;C:\Program Files\Java\jdk1.8.0_101\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Mitov\Visuino;C:\Users\s.zarekar\AppData\Local\Android\sdk\platform-tools;C:\Users\s.zarekar\AppData\Local\Android\sdk\ndk-bundle;C:\Python27;C:\Program Files\Anaconda3;C:\Program Files\Anaconda3\Scripts;C:\Program Files\Anaconda3\Library\bin;C:\Users\s.zarekar\AppData\Roaming\npm;C:\Users\s.zarekar\AppData\Local\.meteor\;C:\Users\s.zarekar\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Docker Toolbox
10 verbose lifecycle marzipano@0.5.1~dev: CWD: C:\Shrikant\VR\Code\new\marzipano
11 silly lifecycle marzipano@0.5.1~dev: Args: [ '/d /s /c', 'dev' ]
12 silly lifecycle marzipano@0.5.1~dev: Returned: code: 1  signal: null
13 info lifecycle marzipano@0.5.1~dev: Failed to exec dev script
14 verbose stack Error: marzipano@0.5.1 dev: `dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\s.zarekar\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\s.zarekar\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid marzipano@0.5.1
16 verbose cwd C:\Shrikant\VR\Code\new\marzipano
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\s.zarekar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v4.4.7
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error marzipano@0.5.1 dev: `dev`
22 error Exit status 1
23 error Failed at the marzipano@0.5.1 dev script 'dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the marzipano package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs marzipano
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls marzipano
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shrikantzarekar** [comment]
Solved it! 
In /scripts/make-swf and /scripts/build
remove get-version
