### ISSUE TITLE
"scripts/release" throws error

### ISSUE THREAD

**Issue by jgreth** [google/marzipano#79]
When i try to do a `npm run release` i get:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'release' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle marzipano@0.5.4~prerelease: marzipano@0.5.4
6 silly lifecycle marzipano@0.5.4~prerelease: no script for prerelease, continuing
7 info lifecycle marzipano@0.5.4~release: marzipano@0.5.4
8 verbose lifecycle marzipano@0.5.4~release: unsafe-perm in lifecycle true
9 verbose lifecycle marzipano@0.5.4~release: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/jan/marzi$
10 verbose lifecycle marzipano@0.5.4~release: CWD: /home/jan/marzipano
11 silly lifecycle marzipano@0.5.4~release: Args: [ '-c', 'scripts/release' ]
12 info lifecycle marzipano@0.5.4~release: Failed to exec release script
13 verbose stack Error: marzipano@0.5.4 release: `scripts/release`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid marzipano@0.5.4
15 verbose cwd /home/jan/marzipano
16 error Linux 4.4.0-77-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "release"
18 error node v6.10.3
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error marzipano@0.5.4 release: `scripts/release`
24 error spawn ENOENT
25 error Failed at the marzipano@0.5.4 release script 'scripts/release'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the marzipano package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     scripts/release
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs marzipano
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls marzipano
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

(trying this on Ubutuntu 16.04 i386)
What could be wrong here?

**Comment by tjgq** [comment]
Did you run `npm install`?

**Comment by jgreth** [comment]
Yes i did. Everything was ok - except two warnings.

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
```

**Comment by tjgq** [comment]
I think that's ok. Chokidar relies on different libraries depending on the platform it runs on.

**Comment by Ankit-Solanki** [comment]
i want to make 360 images like marzipano in offline on localhost, is it possible.
